language: python
python:
  - 2.7
install:
  - pip install -U nose
  - pip install coverage coveralls requests futures sphinx
  - python setup.py develop
before_script:
  - mkdir testrunner
  - cp .coveragerc testrunner/
  - cd testrunner
script:
  - coverage run -m nose.core encore --exe
  - make --directory ../docs html
notifications:
  email:
    - travis-ci@enthought.com
after_success:
  coveralls